### ISSUE TITLE
youtube-dl error with "videoformat"

### ISSUE THREAD

**Issue by Extarys** [RandomNinjaAtk/docker-amvd#19]
I wanted to give this a try mostly out of curiosity (cause I personally don't use/watch music video much) and used my standard archival format string for youtube-dl but it seems there is an error. I looked through the source code and duplicated the download section and played with some variables and it works, but amvd still doesn't like it very much.

```
2021-03-30 18:13:12 =======================START YOUTUBE-DL=========================
ERROR: fixed output name but more than one file to download
```

Config is:
```
  amvd:
    image: randomninjaatk/amvd:latest
    container_name: amvd
    volumes:
      - ./config:/config
      - ./mv:/downloads-amvd
    ports:
      - 8500:80
    environment:
      - PUID=1000
      - PGID=1000
      - AUTOSTART=true
      - SCRIPTINTERVAL=12h
      - SOURCE_CONNECTION=lidarr
      - CountryCode=us
      - RequireVideoMatch=true
      - subtitlelanguage=en
      - videofilter=live
      - WriteNFOs=true
      - USEFOLDERS=true
      - USEVIDEOFOLDERS=true
      - FilePermissions=644
      - FolderPermissions=755
      - MBRAINZMIRROR=https://musicbrainz.org
      - MBRATELIMIT=1
      - LidarrUrl=http://10.0.0.0:8686
      - LidarrAPIkey=000000000000000
      - videoformat="--format (bestvideo[vcodec*=vp9]/bestvideo[vcodec*=av1])[height=1080][fps<=30]+bestaudio/(bestvideo[vcodec*=vp9]/bestvideo[vcodec*=av1])[height=720][fps<=30]+bestaudio/bestvideo[height<1080]+bestaudio"

```

I'm not quite sure what is going on.
