### ISSUE TITLE
Trouble starting up docker image

### ISSUE THREAD

**Issue by bcullman** [RandomNinjaAtk/docker-amvd#30]
same issue as seen here:
https://github.com/RandomNinjaAtk/docker-lidarr-extended/issues/5

Checking portainer, I see the following in the logs:

```
exec /init: exec format error
exec /init: exec format error
exec /init: exec format error
exec /init: exec format error
exec /init: exec format error
exec /init: exec format error
exec /init: exec format error
```

at somepoint the docker container restarts, and this cycle repeats.

my docker-compose file
```
version: "2.1"
services:
  amvd:
    image: randomninjaatk/amvd
    container_name: amvd
    volumes:
      - .config:/config
      - /mnt/music-videos:/downloads-amvd
    environment:
      - PUID=1000
      - PGID=1000
      - AUTOSTART=true
      - SCRIPTINTERVAL=1h
      - SOURCE_CONNECTION=lidarr
      - subtitlelanguage=en
      - videofilter=live
      - USEFOLDERS=true
      - USEVIDEOFOLDERS=false
      - MBRAINZMIRROR=https://musicbrainz.org
      - MBRATELIMIT=1
      - LidarrUrl=http://192.168.0.253:8686
      - LidarrAPIkey=[myLidarrAPIkey]
      - CountryCode=us
    restart: unless-stopped
```

what am i missing here?
